# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: offer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'offer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0boffer.proto\x12\x05offer\"\r\n\x0bPingRequest\"\x1a\n\x0cPingResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"X\n\x0cOfferRequest\x12\x14\n\x0csalary_range\x18\x01 \x01(\t\x12\x10\n\x08\x63ontacts\x18\x02 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x03 \x01(\t\x12\x0f\n\x07\x63omment\x18\x04 \x01(\t\"1\n\rOfferResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2x\n\x0bOfferNotify\x12/\n\x04Ping\x12\x12.offer.PingRequest\x1a\x13.offer.PingResponse\x12\x38\n\x0bNotifyOffer\x12\x13.offer.OfferRequest\x1a\x14.offer.OfferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'offer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=22
  _globals['_PINGREQUEST']._serialized_end=35
  _globals['_PINGRESPONSE']._serialized_start=37
  _globals['_PINGRESPONSE']._serialized_end=63
  _globals['_OFFERREQUEST']._serialized_start=65
  _globals['_OFFERREQUEST']._serialized_end=153
  _globals['_OFFERRESPONSE']._serialized_start=155
  _globals['_OFFERRESPONSE']._serialized_end=204
  _globals['_OFFERNOTIFY']._serialized_start=206
  _globals['_OFFERNOTIFY']._serialized_end=326
# @@protoc_insertion_point(module_scope)
